# Generated by Django 3.2.14 on 2022-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('gas', models.IntegerField(blank=True, null=True)),
                ('fire', models.IntegerField(blank=True, null=True)),
                ('ultrasound', models.IntegerField(blank=True, db_column='ultraSound', null=True)),
                ('person', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('station', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
    ]
