# Generated by Django 3.2.14 on 2022-09-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tram',
        ),
    ]
